// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import "firebase_options.dart";
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for android - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for ios - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for macos - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }
}

const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCNJs_VyFxI7OFAaNxOIoL4KEPtSF0mKUc",
    authDomain: "centerobackend.firebaseapp.com",
    projectId: "centerobackend",
    storageBucket: "centerobackend.appspot.com",
    messagingSenderId: "780428703318",
    appId: "1:780428703318:web:670d5ac13609f2e9fb6df7",
    measurementId: "G-VDDP4KG3DZ");
